create database fasinadb;
use fasinadb;
create table EMP(empid int not null,empname varchar(20),age int);
insert into EMP(empid,empname,age)values(1,'fasina',24);
insert into EMP(empid,empname,age)values(2,'ammmu',25);
update EMP set age = 26 where empid = 2;
insert into EMP(empid,empname,age)values(3,'Appu',23);
insert into EMP(empid,empname,age)values(4,'Raju',23);
insert into EMP(empid,empname,age)values(5,'Anu',22);
select * from EMP;
select * from EMP where age=23;
select * from EMP order by age;
select * from EMP order by age DESC;
insert into EMP values(6,'Appu',21);
update EMP set empname='ammu',age=25 where empid=2;
select empname from EMP;
select empname from EMP where age=23;
select * from EMP where age>23;
select count(empname),age from EMP group by age;
